default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: scraping_development

test:
  <<: *default
  database: scraping_test

production:
  <<: *default
  url: postgres://ua567rq2ilfkv0:p4b216a48b0f325d5723262cb8681e8f27fffa5225aabd6b361cf93a4b42b85cf@cd5gks8n4kb20g.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d3km2pvb3o6pud
